# Generated by Django 4.0.2 on 2022-04-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dev', models.CharField(max_length=200)),
                ('stack', models.CharField(max_length=100)),
                ('modelo_trabalho', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('data_entrada', models.DateTimeField(verbose_name='Data de entrada')),
            ],
        ),
        migrations.CreateModel(
            name='situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Está Trabalhando?')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.dev')),
            ],
        ),
    ]
