# Generated by Django 4.0.2 on 2022-04-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='linguagem_preferida',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
