# Generated by Django 4.0.2 on 2022-04-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_dev_linguagem_preferida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situacao',
            old_name='stack',
            new_name='nome',
        ),
    ]
